config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :users, only: [:show, :destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root to: "static_pages#top"

  get 'about', to: 'static_pages#about'
  get 'cancel_membership', to: 'static_pages#cancel_membership'
  get 'privacy_policy', to: 'static_pages#privacy_policy'
  get 'terms', to: 'static_pages#terms'

  delete 'destroy_user', to: 'static_pages#destroy_user'

  resources :posts do
    resources :comments, only: [:create, :destroy]
    collection do
      get :bookmarks
    end
  end

  resources :questions do
    resources :answers, only: [:create, :destroy]
  end

  resources :cities, only: [:index]

  resources :bookmarks, only: [:create, :destroy]

  resources :notifications, only: [:index] do
    collection do
      patch :mark_as_read
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def top
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true).includes(:user, :prefecture, :city).order(created_at: :desc).limit(15)
    @questions = Question.all.includes(:user, :area).order(created_at: :desc)
    @question_pickups = Question.includes(:area).order('RAND()').limit(1)
  end

  def about
  end

  def cancel_membership
  end

  def destroy_user
    current_user.destroy
    redirect_to root_path, notice: t('devise.registrations.destroyed'), status: :see_other
  end

  def privacy_policy
  end

  def terms
  end
end

app/views/static_pages/about.html.erb
<% breadcrumb :about %>
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <div class="card shadow border-0" style="background-color:rgba(255,255,255,0.8)">
        <div class="card-body p-5 text-center">
          <h2 class="mb-5 about-title">このサイトについて</h2>
          <p class="mb-2">このサイトはユーザーが今まで住んだことのある地域、現在住んでいる地域などのあるあるやエピソードを共有するアプリです。</p>
          <p>制作者の出身が北海道なのですが、あまりにも広いため同じ北海道出身でも特色や生活には違いがあると感じていました。他の地域も市区町村によってさまざまな違いがあると思います。</p>
          <p class="mb-5">みなさんにゆかりのある地域について教えていただけると嬉しいです。</p>
          <p class="mb-3">不具合やご意見などありましたら下記までご連絡いただけますと幸いです。</p>
          <div class="mb-5">
            <%= link_to "お問い合わせフォーム", "https://forms.gle/bCbByjphU7YuJR44A", target: :_blank, class: "link-dark" %>
          </div>
          <p class="about-caution">批判や差別を助長する投稿、公序良俗に反する内容や過度にネガティブな内容の投稿はご遠慮ください。<br/>
          内容により削除させて頂く場合がございます。</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/cancel_membership.erb
<% breadcrumb :cancel_menbership %>
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <article class="card shadow border-0">
        <div class="card-body p-5 text-center">
          <div class="pb-4">
            <h2>退会しますか？</h2>
          </div>
          <div>
            <p>退会すると、投稿やコメント、質問、回答も削除されます</p>
            <p>本当によろしいですか？</p>
          </div>
          <div>
            <%= link_to "退会する", destroy_user_path, data: { turbo_method: :delete, turbo_confirm: "退会しますか？" }, class: "btn btn-danger mb-3", style: "width: 200px;" %>
          </div>
          <div>
            <%= link_to "ホームに戻る", root_path, class: "btn btn-light", style: "width: 200px; background-color: #D9D9D9;" %>
        </div>
      </article>
    </div>
  </div>
</div>

app/views/static_pages/privacy_policy.html.erb
<% breadcrumb :privacy_policy %>
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <article class="card shadow border-0">
        <div class="card-body p-5">
          <h2 class="pb-4 text-center">プライバシーポリシー</h2>
          <h5 class="mb-3">ユーザーから取得する情報</h5>
          <p>本サービスは、ユーザーから以下の情報を取得します。</p>
          <ul>
            <li>氏名(ニックネームやペンネームも含む)</li>
            <li>メールアドレス</li>
            <li>外部サービスでユーザーが利用するID、その他外部サービスのプライバシー設定によりユーザーが連携先に開示を認めた情報</li>
            <li>Cookie(クッキー)を用いて生成された識別情報</li>
            <li>運営者ウェブサイトの滞在時間、入力履歴、購買履歴等の運営者ウェブサイトにおけるユーザーの行動履歴</li>
          </ul>
          <h5 class="mb-3">ユーザーの情報を利用する目的</h5>
          <p>運営者は、ユーザーから取得した情報を、以下の目的のために利用します。</p>
          <ul>
            <li>本サービスに関する登録の受付、ユーザーの本人確認、認証のため</li>
            <li>ユーザーの利用履歴を管理するため</li>
            <li>本サービスにおけるユーザーの行動履歴を分析し、本サービスの維持改善に役立てるため</li>
            <li>ユーザーからのお問い合わせに対応するため</li>
            <li>運営者の規約や法令に違反する行為に対応するため</li>
            <li>本サービスの変更、提供中止、終了、契約解除をご連絡するため</li>
            <li>利用規約の変更等を通知するため</li>
            <li>以上の他、本サービスの提供、維持、保護及び改善のため</li>
          </ul>
          <h5 class="mb-3">安全管理のために講じた措置</h5>
          <p>運営者が、ユーザーから取得した情報に関して安全管理のために講じた措置につきましては、末尾記載のお問い合わせ先にご連絡をいただきましたら、法令の定めに従い個別にご回答させていただきます。</p>
          <h5 class="mb-3">第三者提供</h5>
          <p>運営者は、ユーザーから取得する情報のうち、個人データ（個人情報保護法第１６条第３項）に該当するものついては、あらかじめユーザーの同意を得ずに、第三者（日本国外にある者を含みます。）に提供しません。但し、次の場合は除きます。</p>
          <ul>
            <li>個人データの取扱いを外部に委託する場合</li>
            <li>本サービスが買収された場合</li>
            <li>事業パートナーと共同利用する場合（具体的な共同利用がある場合は、その内容を別途公表します。）</li>
            <li>その他、法律によって合法的に第三者提供が許されている場合</li>
          </ul>
          <h5 class="mb-3">プライバシーポリシーの変更</h5>
          <p>運営者は、必要に応じて、このプライバシーポリシーの内容を変更します。この場合、変更後のプライバシーポリシーの施行時期と内容を適切な方法により周知または通知します。</p>
          <h5 class="mb-3">お問い合わせ</h5>
          <p>ユーザーの情報の開示、情報の訂正、利用停止、削除をご希望の場合は、以下のメールアドレスにご連絡ください。</p>
          <p>e-mail</p>
          <p>jimotter.info@gmail.com</p>
          <p>この場合、必ず、運営者が指定する方法により、ご本人からのご請求であることの確認をさせていただきます。</p>
          <p>2024年07月15日 制定</p>
        </div>
      </article>
    </div>
  </div>
</div>

app/views/static_pages/terms.html.erb
<% breadcrumb :terms %>
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <article class="card shadow border-0">
        <div class="card-body p-5">
          <h2 class="pb-4 text-center">利用規約</h2>
          <p>この利用規約（以下、「本規約」といいます。）は、このウェブサイト上で提供するサービス「Jimotter-地域あるある投稿アプリ-」（以下、「本サービス」といいます。）の利用条件を定めるものです。登録ユーザーの皆さま（以下、「ユーザー」といいます。）には、本規約に従って、本サービスをご利用いただきます。</p>
          <h4 class="py-3">第1条（適用）</h4>
            <ol>
              <li class="mb-3">本規約は、ユーザーと運営者との間の本サービスの利用に関わる一切の関係に適用されるものとします。</li>
              <li class="mb-3">運営者は本サービスに関し、本規約のほか、ご利用にあたってのルール等、各種の定め（以下、「個別規定」といいます。）をすることがあります。これら個別規定はその名称のいかんに関わらず、本規約の一部を構成するものとします。</li>
              <li class="mb-3">本規約の規定が前条の個別規定の規定と矛盾する場合には、個別規定において特段の定めなき限り、個別規定の規定が優先されるものとします。</li>
            </ol>
          <h4 class="py-3">第2条（利用登録）</h4>
            <ol>
              <li class="mb-3">本サービスにおいては、登録希望者が本規約に同意の上、運営者の定める方法によって利用登録を申請し、運営者がこの承認を登録希望者に通知することによって、利用登録が完了するものとします。</li>
              <li class="mb-3">運営者は、利用登録の申請者に以下の事由があると判断した場合、利用登録の申請を承認しないことがあり、その理由については一切の開示義務を負わないものとします。</li>
              <ol>
                <li class="mb-3">利用登録の申請に際して虚偽の事項を届け出た場合</li>
                <li class="mb-3">本規約に違反したことがある者からの申請である場合</li>
                <li class="mb-3">その他、運営者が利用登録を相当でないと判断した場合</li>
              </ol>
            </ol>
          <h4 class="py-3">第3条（ユーザーIDおよびパスワードの管理）</h4>
            <ol>
              <li class="mb-3">ユーザーは、自己の責任において、本サービスのユーザーIDおよびパスワードを適切に管理するものとします。</li>
              <li class="mb-3">ユーザーは、いかなる場合にも、ユーザーIDおよびパスワードを第三者に譲渡または貸与し、もしくは第三者と共用することはできません。運営者は、ユーザーIDとパスワードの組み合わせが登録情報と一致してログインされた場合には、そのユーザーIDを登録しているユーザー自身による利用とみなします。</li>
              <li class="mb-3">ユーザーID及びパスワードが第三者によって使用されたことによって生じた損害は、運営者に故意又は重大な過失がある場合を除き、運営者は一切の責任を負わないものとします。</li>
            </ol>
          <h4 class="py-3">第4条（禁止事項）</h4>
            <p>ユーザーは、本サービスの利用にあたり、以下の行為をしてはなりません。</p>
            <ol>
              <li class="mb-3">法令または公序良俗に違反する行為</li>
              <li class="mb-3">犯罪行為に関連する行為</li>
              <li class="mb-3">運営者、本サービスの他のユーザー、または第三者のサーバーまたはネットワークの機能を破壊したり、妨害したりする行為</li>
              <li class="mb-3">運営者のサービスの運営を妨害するおそれのある行為</li>
              <li class="mb-3">他のユーザーに関する個人情報等を収集または蓄積する行為</li>
              <li class="mb-3">不正アクセスをし、またはこれを試みる行為</li>
              <li class="mb-3">他のユーザーに成りすます行為</li>
              <li class="mb-3">運営者のサービスに関連して、反社会的勢力に対して直接または間接に利益を供与する行為</li>
              <li class="mb-3">運営者、本サービスの他のユーザーまたは第三者の知的財産権、肖像権、プライバシー、名誉その他の権利または利益を侵害する行為</li>
              <li class="mb-3">以下の表現を含み、または含むと運営者が判断する内容を本サービス上に投稿し、または送信する行為</li>
                <ol>
                  <li class="mb-3">過度に暴力的な表現</li>
                  <li class="mb-3">露骨な性的表現</li>
                  <li class="mb-3">人種、国籍、信条、性別、社会的身分、門地等による差別につながる表現</li>
                  <li class="mb-3">自殺、自傷行為、薬物乱用を誘引または助長する表現</li>
                  <li class="mb-3">その他反社会的な内容を含み他人に不快感を与える表現</li>
                </ol>
              <li class="mb-3">以下を目的とし、または目的とすると運営者が判断する行為</li>
                <ol>
                  <li class="mb-3">営業、宣伝、広告、勧誘、その他営利を目的とする行為（運営者の認めたものを除きます。）</li>
                  <li class="mb-3">性行為やわいせつな行為を目的とする行為</li>
                  <li class="mb-3">他のユーザーとの出会いや交際を目的とする行為</li>
                  <li class="mb-3">他のユーザーに対する嫌がらせや誹謗中傷を目的とする行為</li>
                  <li class="mb-3">運営者、本サービスの他のユーザー、または第三者に不利益、損害または不快感を与えることを目的とする行為</li>
                  <li class="mb-3">その他本サービスが予定している利用目的と異なる目的で本サービスを利用する行為</li>
                </ol>
              <li class="mb-3">宗教活動または宗教団体への勧誘行為</li>
              <li class="mb-3">その他、運営者が不適切と判断する行為</li>
            </ol>
          <h4 class="py-3">第5条（本サービスの提供の停止等）</h4>
            <ol>
              <li class="mb-3">運営者は、以下のいずれかの事由があると判断した場合、ユーザーに事前に通知することなく本サービスの全部または一部の提供を停止または中断することができるものとします。</li>
                <ol>
                  <li class="mb-3">本サービスにかかるコンピュータシステムの保守点検または更新を行う場合</li>
                  <li class="mb-3">地震、落雷、火災、停電または天災などの不可抗力により、本サービスの提供が困難となった場合</li>
                  <li class="mb-3">コンピュータまたは通信回線等が事故により停止した場合</li>
                  <li class="mb-3">その他、運営者が本サービスの提供が困難と判断した場合</li>
                </ol>
              <li class="mb-3">運営者は、本サービスの提供の停止または中断により、ユーザーまたは第三者が被ったいかなる不利益または損害についても、一切の責任を負わないものとします。</li>
            </ol>
          <h4 class="py-3">第6条（著作権）</h4>
            <ol>
              <li class="mb-3">ユーザーは、自ら著作権等の必要な知的財産権を有するか、または必要な権利者の許諾を得た文章、画像や映像等の情報に関してのみ、本サービスを利用し、投稿ないしアップロードすることができるものとします。</li>
              <li class="mb-3">ユーザーが本サービスを利用して投稿ないしアップロードした文章、画像、映像等の著作権については、当該ユーザーその他既存の権利者に留保されるものとします。ただし、運営者は、本サービスを利用して投稿ないしアップロードされた文章、画像、映像等について、本サービスの改良、品質の向上、または不備の是正等ならびに本サービスの周知宣伝等に必要な範囲で利用できるものとし、ユーザーは、この利用に関して、著作者人格権を行使しないものとします。</li>
              <li class="mb-3">前項本文の定めるものを除き、本サービスおよび本サービスに関連する一切の情報についての著作権およびその他の知的財産権はすべて運営者または運営者にその利用を許諾した権利者に帰属し、ユーザーは無断で複製、譲渡、貸与、翻訳、改変、転載、公衆送信（送信可能化を含みます。）、伝送、配布、出版、営業使用等をしてはならないものとします。</li>
            </ol>
          <h4 class="py-3">第7条（利用制限および登録抹消）</h4>
            <ol>
              <li class="mb-3">運営者は、ユーザーが以下のいずれかに該当する場合には、事前の通知なく、投稿データを削除し、ユーザーに対して本サービスの全部もしくは一部の利用を制限しまたはユーザーとしての登録を抹消することができるものとします。</li>
                <ol>
                  <li class="mb-3">本規約のいずれかの条項に違反した場合</li>
                  <li class="mb-3">登録事項に虚偽の事実があることが判明した場合</li>
                  <li class="mb-3">運営者からの連絡に対し、一定期間返答がない場合</li>
                  <li class="mb-3">本サービスについて、最終の利用から一定期間利用がない場合</li>
                  <li class="mb-3">その他、運営者が本サービスの利用を適当でないと判断した場合</li>
                </ol>
              <li class="mb-3">前項各号のいずれかに該当した場合、ユーザーは、当然に運営者に対する一切の債務について期限の利益を失い、その時点において負担する一切の債務を直ちに一括して弁済しなければなりません。</li>
              <li class="mb-3">運営者は、本条に基づき運営者が行った行為によりユーザーに生じた損害について、一切の責任を負いません。</li>
            </ol>
          <h4 class="py-3">第8条（退会）</h4>
            <p>ユーザーは、運営者の定める退会手続により、本サービスから退会できるものとします。</p>
          <h4 class="py-3">第9条（保証の否認および免責事項）</h4>
            <ol>
              <li class="mb-3">運営者は、本サービスに事実上または法律上の瑕疵（安全性、信頼性、正確性、完全性、有効性、特定の目的への適合性、セキュリティなどに関する欠陥、エラーやバグ、権利侵害などを含みます。）がないことを明示的にも黙示的にも保証しておりません。</li>
              <li class="mb-3">運営者は、本サービスに起因してユーザーに生じたあらゆる損害について、運営者の故意又は重過失による場合を除き、一切の責任を負いません。ただし、本サービスに関する運営者とユーザーとの間の契約（本規約を含みます。）が消費者契約法に定める消費者契約となる場合、この免責規定は適用されません。</li>
              <li class="mb-3">前項ただし書に定める場合であっても、運営者は、運営者の過失（重過失を除きます。）による債務不履行または不法行為によりユーザーに生じた損害のうち特別な事情から生じた損害（運営者またはユーザーが損害発生につき予見し、または予見し得た場合を含みます。）について一切の責任を負いません。また、運営者の過失（重過失を除きます。）による債務不履行または不法行為によりユーザーに生じた損害の賠償は、ユーザーから当該損害が発生した月に受領した利用料の額を上限とします。</li>
              <li class="mb-3">運営者は、本サービスに関して、ユーザーと他のユーザーまたは第三者との間において生じた取引、連絡または紛争等について一切責任を負いません。</li>
            </ol>
          <h4 class="py-3">第10条（サービス内容の変更等）</h4>
            <p>運営者は、ユーザーへの事前の告知をもって、本サービスの内容を変更、追加または廃止することがあり、ユーザーはこれを承諾するものとします。</p>
          <h4 class="py-3">第11条（利用規約の変更）</h4>
            <ol>
              <li class="mb-3">運営者は以下の場合には、ユーザーの個別の同意を要せず、本規約を変更することができるものとします。</li>
                <ol>
                  <li class="mb-3">本規約の変更がユーザーの一般の利益に適合するとき。</li>
                  <li class="mb-3">本規約の変更が本サービス利用契約の目的に反せず、かつ、変更の必要性、変更後の内容の相当性その他の変更に係る事情に照らして合理的なものであるとき。</li>
                </ol>
              <li class="mb-3">運営者はユーザーに対し、前項による本規約の変更にあたり、事前に、本規約を変更する旨及び変更後の本規約の内容並びにその効力発生時期を通知します。</li>
            </ol>
          <h4 class="py-3">第12条（個人情報の取扱い）</h4>
            <p>運営者は、本サービスの利用によって取得する個人情報については、運営者「プライバシーポリシー」に従い適切に取り扱うものとします。</p>
          <h4 class="py-3">第13条（通知または連絡）</h4>
            <p>ユーザーと運営者との間の通知または連絡は、運営者の定める方法によって行うものとします。運営者は、ユーザーから、運営者が別途定める方式に従った変更届け出がない限り、現在登録されている連絡先が有効なものとみなして当該連絡先へ通知または連絡を行い、これらは、発信時にユーザーへ到達したものとみなします。</p>
          <h4 class="py-3">第14条（権利義務の譲渡の禁止）</h4>
            <p>ユーザーは、運営者の書面による事前の承諾なく、利用契約上の地位または本規約に基づく権利もしくは義務を第三者に譲渡し、または担保に供することはできません。</p>
          <h4 class="py-3">第15条（準拠法・裁判管轄）</h4>
            <ol>
              <li class="mb-3">本規約の解釈にあたっては、日本法を準拠法とします。</li>
              <li class="mb-3">本サービスに関して紛争が生じた場合には、運営者の本店所在地を管轄する裁判所を専属的合意管轄とします。</li>
            </ol>
          <p class="text-end">以上</p>
        </div>
      </article>
    </div>
  </div>
</div>

app/views/static_pages/top.html.erb
<%= javascript_include_tag "tutorial" %>
<%= javascript_include_tag "searchform" %>

<div class="loader-wrap">
  <div class="loader">Loading...</div>
</div>

<div class="top-background">
  <div class="container-fluid question-pickup">
    <div class="row">
      <% @question_pickups.each do |question_pickup| %>
        <div class="question-pickup-text">
          <button>pickup</button>
          <%= link_to "#{question_pickup.content}", question_path(question_pickup) %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="container d-flex flex-column justify-content-center" style="min-height: 10vh;">
    <div class="row">    
      <div class="jumbotron jumbotron-fluid col-12">
        <div class="col-lg-7 col-md-7">
          <div class="text-center custom-title-top"><span>わたしのじもと、</span></div>
          <div class="text-center custom-title-under mb-3"><span>知名度低すぎ…!?</span></div>
          <div class="text-center mb-4 title-text">
          <h6>都道府県あるあるはよくあるけど、<br/>
          市区町村で特徴はさまざま。<br/>
          あなたの地元のあるあるをみんなに共有しよう！</h6>
          </div>
        
          <div class="d-flex justify-content-center">
            <% if user_signed_in? %>
                <div class="d-flex flex-column align-items-center" id="post-button">
                  <div>
                    <%= link_to "あるあるを投稿", new_post_path, class: "btn text-light rounded-pill post-button mb-3" %>
                  </div>
                  <div>
                    <%= link_to "みんなに質問", new_question_path, class: "btn text-light rounded-pill post-button" %>
                  </div>
                </div>
            <% else %>
              <%= link_to "ログインしてアピールする", new_user_session_path, class: "btn btn-primary rounded-pill mt-2 mb-3 post-button", id: "login" %>
            <% end %>
          </div>
        </div>
        <div class="d-flex justify-content-center">
          <div class="mt-4">
            <h3 class="text-center search-title">地域で検索</h3>
            <h6 class="text-center search-title">都道府県のみでも検索できます</h6>
          </div>
        </div>
        <div class="d-flex justify-content-center">
          <div class="mt-2 mb-4">
            <%= render 'posts/searchform', q: @q %>
          </div>
        </div>
      </div>

      <div class="col-sm-12">
        <ul class="nav nav-pills" id="myTab" role="tablist">
          <li class="nav-item" role="presentation">
            <button type="button" class="nav-link active" id="post-tab" data-bs-toggle="pill" href="#post" role="tab" aria-controls="post" aria-selected="true">新着投稿</button>
          </li>
          <li class="nav-item" role="presentation">
            <button type="button" class="nav-link ms-2" id="question-tab" data-bs-toggle="pill" href="#question" role="tab" aria-controls="question" aria-selected="false">新着質問</button>
          </li>
        </ul>

        <div class="tab-content" id="myTabContent">
          <div class="tab-pane fade show active mt-2" id="post" role="tabpanel" aria-labelledby="post-tab" tabindex="0">
            <%= render partial: 'posts/post', collection: @posts, as: :post %>
            <%= link_to posts_path, class: "text-center ms-auto text-decoration-none" do %>
              <h6>もっと見る</h6>
            <% end %>
          </div>
          <div class="tab-pane fade question-tab mt-2" id="question" role="tabpanel" aria-labelledby="question-tab" tabindex="0">
            <%= render 'questions/question', questions: @questions %>
            <%= link_to questions_path, class: "text-center ms-auto text-decoration-none" do %>
              <h6>もっと見る</h6>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>