config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :users, only: [:show, :destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root to: "static_pages#top"

  get 'about', to: 'static_pages#about'
  get 'cancel_membership', to: 'static_pages#cancel_membership'
  get 'privacy_policy', to: 'static_pages#privacy_policy'
  get 'terms', to: 'static_pages#terms'

  delete 'destroy_user', to: 'static_pages#destroy_user'

  resources :posts do
    resources :comments, only: [:create, :destroy]
    collection do
      get :bookmarks
    end
  end

  resources :questions do
    resources :answers, only: [:create, :destroy]
  end

  resources :cities, only: [:index]

  resources :bookmarks, only: [:create, :destroy]

  resources :notifications, only: [:index] do
    collection do
      patch :mark_as_read
    end
  end
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= bootstrap_alert(key) %> alert-dismissible fade show mb-0">
    <span><%= value %></span>
    <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer id='footer' class='footer-bottom mt-5 footer-color'>
  <div class='container py-3'>
    <ul class='nav row justify-content-between footer-list'>
      <% if user_signed_in? %>
        <li class="nav-item col-lg-3 col-sm-6">
          <%= link_to "退会", cancel_membership_path, class: "nav-link text-light text-center" %>
        </li>
        <li class="nav-item col-lg-3 col-sm-6">
          <%= link_to "利用規約", terms_path, class: "nav-link text-light text-center" %>
        </li>
        <li class="nav-item col-lg-3 col-sm-6">
          <%= link_to "プライバシポリシー", privacy_policy_path, class: "nav-link text-light text-center" %>
        </li>
        <li class="nav-item col-lg-3 col-sm-6">
          <%= link_to "お問い合わせ", "https://forms.gle/bCbByjphU7YuJR44A", class: "nav-link text-light text-center", target: :_blank, rel: "noopener noreferrer" %>
        </li>
      <% else %>
        <li class="nav-item col-lg-4 col-sm-6">
          <%= link_to "利用規約", terms_path, class: "nav-link text-light text-center" %>
        </li>
        <li class="nav-item col-lg-4 col-sm-6">
          <%= link_to "プライバシポリシー", privacy_policy_path, class: "nav-link text-light text-center" %>
        </li>
        <li class="nav-item col-lg-4 col-sm-12">
          <%= link_to "お問い合わせ", "https://forms.gle/bCbByjphU7YuJR44A", class: "nav-link text-light text-center", target: :_blank, rel: "noopener noreferrer" %>
        </li>
      <% end %>
    </ul>
    <div class="text-center text-light pt-5">
    © 2024 Jimotter
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <div class="fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark header-color shadow">
      <div class="container">
        <%= link_to image_tag('app-logo.svg', class: 'navbar-brand app-logo', alt: '地域投稿あるあるアプリJimotter'), root_path %>

        <% if current_user %>
          <a href="#" class="nav-link text-light ms-auto mx-3 d-lg-none" data-bs-toggle="modal" data-bs-target="#notificationsModal">
            <% if current_user.notifications.where(checked: false).exists? %>
              <i id="notification-icon-small" class="fa-solid fa-bell faa-wrench animated" style="color: #f2ee7d;" data-bs-toggle="tooltip" data-bs-placement="bottom" title="通知"></i>
            <% else %>
              <i id="notification-icon-small" class="fa-solid fa-bell" style="color: #FFF;" data-bs-toggle="tooltip" data-bs-placement="bottom" title="通知"></i>
            <% end %>
          </a>
        <% end %>

        <% if current_page?(root_path) %>
          <% if user_signed_in? %>
            <i class="fa-solid fa-circle-question nav-link d-lg-none " style="color: #ffffff; margin-right: 15px;" id="start-tour-sm" data-bs-toggle="tooltip" data-bs-placement="bottom" title="チュートリアル"></i>
          <% else %>
            <i class="fa-solid fa-circle-question ms-auto nav-link d-lg-none " style="color: #ffffff; margin-right: 15px;" id="start-tour-sm" data-bs-toggle="tooltip" data-bs-placement="bottom" title="チュートリアル"></i>
          <% end %>
        <% end %>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ms-auto main-nav align-items-center">
            <% if current_user %>
              <li class="nav-item">
                <a href="#" class="nav-link text-light d-none d-lg-inline" data-bs-toggle="modal" data-bs-target="#notificationsModal">
                  <% if current_user.notifications.where(checked: false).exists? %>
                    <i id="notification-icon-large" class="fa-solid fa-bell faa-wrench animated" style="color: #f2ee7d;" data-bs-toggle="tooltip" data-bs-placement="bottom" title="通知"></i>
                  <% else %>
                    <i id="notification-icon-large" class="fa-solid fa-bell" style="color: #FFF;" data-bs-toggle="tooltip" data-bs-placement="bottom" title="通知"></i>
                  <% end %>
                </a>
              </li>
            <% end %>
            <% if current_page?(root_path) %>
              <li>
                <i class="fa-solid fa-circle-question nav-link d-lg-inline" style="color: #ffffff;" id="start-tour-lg" data-bs-toggle="tooltip" data-bs-placement="bottom" title="チュートリアル"></i>
              </li>
            <% end %>
            <li class="nav-item">
              <%= link_to "サイトについて", about_path, class: 'nav-link header-text' %>
            </li>
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to "マイページ", user_path(current_user.id), class: 'nav-link header-text' %>
              </li>
              <li class="nav-item">
                <%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete }, class: 'nav-link header-text' %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "ログイン", new_user_session_path, class: 'nav-link header-text' %>
              </li>
              <li class="nav-item">
                <%= link_to "新規登録", new_user_registration_path, class: 'nav-link header-text' %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </div>
</header>

<style>
@media (min-width: 992px) {
  .d-lg-none {
    display: none !important;
  }
}

@media (max-width: 991.98px) {
  .d-lg-inline {
    display: none !important;
  }
}
</style>