config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :users, only: [:show, :destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root to: "static_pages#top"

  get 'about', to: 'static_pages#about'
  get 'cancel_membership', to: 'static_pages#cancel_membership'
  get 'privacy_policy', to: 'static_pages#privacy_policy'
  get 'terms', to: 'static_pages#terms'

  delete 'destroy_user', to: 'static_pages#destroy_user'

  resources :posts do
    resources :comments, only: [:create, :destroy]
    collection do
      get :bookmarks
    end
  end

  resources :questions do
    resources :answers, only: [:create, :destroy]
  end

  resources :cities, only: [:index]

  resources :bookmarks, only: [:create, :destroy]

  resources :notifications, only: [:index] do
    collection do
      patch :mark_as_read
    end
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question
  belongs_to :prefecture
  belongs_to :city

  has_one :notification, as: :subject, dependent: :destroy
  after_create_commit :create_notifications

  validates :content, presence: true, length: { maximum: 355 }

  private

  def create_notifications
    Notification.create(subject: self, user: question.user, action_type: :answered_to_own_question)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!, only: [:create]

  def create
    @answer = current_user.answers.build(answer_params)
    @answer.question = Question.find(params[:question_id])
    if @answer.save
      redirect_to @answer.question, notice: t('.success')
    else
      redirect_to @answer.question, alert: t('.failed')
    end
  end

  def destroy
    @answer = current_user.answers.find(params[:id])
    @answer.destroy!
  end

  private

  def answer_params
    params.require(:answer).permit(:prefecture_id, :city_id, :content).merge(question_id: params[:question_id])
  end
end

app/views/answers/_answer.html.erb
<div id="answer-<%= answer.id %>">
  <div class="border mb-2">
    <div class="d-flex mb-2">
      <%= link_to answer.user&.name, user_path(answer.user), class: "link-dark name-link mt-3 mb-1 px-4" %>
      <div class="area-box mt-3 mb-1"><%= answer.prefecture.name %></div>
      <div class="area-box mt-3 mx-2 mb-1"><%= answer.city.name %></div>
    </div>
    <p class="mb-1 px-4"><%= answer.content %></p>
    <div class="d-flex px-4">
      <small class="mb-2 ms-auto"><%= l answer.created_at %></small>
    </div>
    <div class="d-flex flex-row-reverse px-4">
      <% if current_user && current_user.own?(answer) %>
        <%= link_to question_answer_path(answer.question, answer), data: { turbo_method: :delete, turbo_confirm: "削除しますか？", bs_toggle: "tooltip", bs_placement: "top" }, title: "回答を削除" do %>
          <i class="fa-solid fa-trash-can mb-3" style="color: #185a9d;"></i>
        <% end %>
      <% end %>
      <%= link_to "https://twitter.com/intent/tweet?text=#{ answer.question.content }%0a%0a【#{ ERB::Util.url_encode(answer.prefecture.name) }】【#{ ERB::Util.url_encode(answer.city.name) }】%0a#{ ERB::Util.url_encode(answer.content) }%0a%0a%23Jimotter%0a&url=#{ ERB::Util.url_encode(question_url(answer.question)) }", target: '_blank', rel: "noopener noreferrer", data: { bs_toggle: "tooltip", bs_placement: "top" }, title: "Xで共有する" do %>
        <i class="fa-brands fa-x-twitter" style="color: #185a9d; margin-right: 10px;"></i>
      <% end %>
    </div>
  </div>
</div>

app/views/answers/_form.html.erb
<div id="answer-form">
  <%= form_with model: answer, url: question_answers_path(question) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="form-group">
        <div class="mb-2">
          <%= f.collection_select :prefecture_id, Prefecture.all, :id, :name, { prompt: "都道府県を選択" }, { class: "form-select" } %>
        </div>
        <div class="mb-2">
          <%= f.collection_select :city_id, [], :id, :name, { prompt: "市区町村を選択" }, { class: "form-select" } %>
        </div>
      <div class="mb-2">
        <%= f.text_area :content, class: 'form-control', rows:4, placeholder: "回答を入力" %>
      </div>
      <div class="d-flex justify-content-center">
        <%= f.submit "回答", class: "btn btn-primary postcreate-button mb-5 w-100" %>
      </div>
    </div>
  <% end %>
</div>

<script>
document.addEventListener("turbo:load", function() {
  var prefectureSelect = document.querySelector('select[name="answer[prefecture_id]"]');
  var citySelect = document.querySelector('select[name="answer[city_id]"]');

  if (prefectureSelect && citySelect) {
    prefectureSelect.addEventListener("change", function() {
      var prefectureId = this.value;

      if (prefectureId) {
        fetch(`/cities.json?prefecture_id=${prefectureId}`)
          .then(response => response.json())
          .then(data => {
            citySelect.innerHTML = '<option value="">市区町村を選択</option>';
            data.forEach(function(city) {
              var option = document.createElement('option');
              option.value = city.id;
              option.text = city.name;
              citySelect.appendChild(option);
            });
          })
          .catch(error => console.error('Error:', error));
      } else {
        citySelectHTML = '<option value="">市区町村を選択</option>';
      }
    });
  }
});
</script>

app/views/answers/destroy.turbo_stream.erb
<%= turbo_stream.remove "answer-#{@answer.id}" do %>
<% end %>