config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :users, only: [:show, :destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root to: "static_pages#top"

  get 'about', to: 'static_pages#about'
  get 'cancel_membership', to: 'static_pages#cancel_membership'
  get 'privacy_policy', to: 'static_pages#privacy_policy'
  get 'terms', to: 'static_pages#terms'

  delete 'destroy_user', to: 'static_pages#destroy_user'

  resources :posts do
    resources :comments, only: [:create, :destroy]
    collection do
      get :bookmarks
    end
  end

  resources :questions do
    resources :answers, only: [:create, :destroy]
  end

  resources :cities, only: [:index]

  resources :bookmarks, only: [:create, :destroy]

  resources :notifications, only: [:index] do
    collection do
      patch :mark_as_read
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  before_save :geocode

  belongs_to :user
  belongs_to :prefecture
  belongs_to :city
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_one :notification, as: :subject, dependent: :destroy

  validates :content, presence: true, length: { maximum: 200 }

  # rubocop:disable Lint/UnusedMethodArgument
  def self.ransackable_attributes(auth_object = nil)
    %w(prefecture city prefecture_id city_id)
  end
  # rubocop:enable Lint/UnusedMethodArgument

  private

  def geocode
    prefecture_name = prefecture.name
    city_name = city.name

    address = "#{city_name}, #{prefecture_name}, Japan"

    response = RestClient.get 'https://maps.googleapis.com/maps/api/geocode/json', { params: { address: address, key: ENV['GEOCODE_API_KEY'] } }
    if response.code == 200
      data = JSON.parse(response.body)
      Rails.logger.debug "Geocode response: #{data}" # レスポンスのログ出力
      if data['status'] == 'OK' && data['results'].any?
        self.latitude = data['results'][0]['geometry']['location']['lat']
        self.longitude = data['results'][0]['geometry']['location']['lng']
      else
        Rails.logger.error "Geocode failed for address: #{address}"
      end
    else
      Rails.logger.error "Geocode request failed with code: #{response.code}"
    end
  rescue RestClient::ExceptionWithResponse => e
    Rails.logger.error "Geocode request failed: #{e.response}"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    # @posts = Post.all.includes(:user,:prefecture,:city).order(created_at: :desc)
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true).includes(:user, :prefecture, :city).order(created_at: :desc).page(params[:page]).per(10)

    @prefecture_id = params[:q][:prefecture_id_eq] if params[:q].present?
    @city_id = params[:q][:city_id_eq] if params[:q].present?

    @prefecture = Prefecture.find_by(id: @prefecture_id) if @prefecture_id.present?
    @city = City.find_by(id: @city_id) if @city_id.present?

    @count = @posts.count
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
  end

  def new
    @post = Post.new
  end

  def edit
    @post = current_user.posts.find(params[:id])
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to @post, notice: t('.success')
    else
      flash.now[:alert] = t('.failed')
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @post = current_user.posts.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post), notice: t('.success')
    else
      flash.now[:alert] = t('failed')
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy!
    redirect_to root_path, status: :see_other, notice: t('.success')
  end

  def bookmarks
    @bookmark_posts = current_user.bookmark_posts.includes(:user).order(created_at: :desc)
  end

  private

  def post_params
    params.require(:post).permit(:prefecture_id, :city_id, :content)
  end
end

app/views/posts/_form.html.erb
<%= form_with model: @post, local: true do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="form-group">
    <div class="mb-3">
      <%= f.collection_select :prefecture_id, Prefecture.all, :id, :name, { prompt: "都道府県を選択" }, { class: "form-select" } %>
    </div>
    <div class="mb-3">
      <%= f.collection_select :city_id, City.where(prefecture_id: @post.prefecture_id), :id, :name, { prompt: "市区町村を選択" }, { class: "form-select", selected: @post.city_id } %>
    </div>
    <div class="mb-3">
      <%= f.text_area :content, class: 'form-control', rows: 7, placeholder: "投稿内容を入力" %>
    </div>
    <%= f.submit "投稿", class: "btn btn-primary postcreate-button w-100 mt-3 mb-5 text-light" %>
  </div>
<% end %>

<script>
document.addEventListener("turbo:load", function() {
  const prefectureSelect = document.querySelector('select[name="post[prefecture_id]"]');
  const citySelect = document.querySelector('select[name="post[city_id]"]');

  if (!prefectureSelect || !citySelect) {
    return;
  }

  function loadCities(prefectureId, selectedCityId = null) {
    fetch(`/cities.json?prefecture_id=${prefectureId}`)
      .then(response => response.json())
      .then(data => {
        citySelect.innerHTML = '<option value="" selected>市区町村を選択</option>';
        data.forEach(function(city) {
          const option = document.createElement('option');
          option.value = city.id;
          option.text = city.name;
          if (selectedCityId && city.id == selectedCityId) {
            option.selected = true;
          }
          citySelect.appendChild(option);
        });
      })
      .catch(error => console.error('Error:', error));
  }

  prefectureSelect.addEventListener("change", function() {
    const prefectureId = this.value;
    if (prefectureId) {
      loadCities(prefectureId);
    }
  });

  // もし編集フォームの初期表示で都道府県が設定されている場合
  if (prefectureSelect.value) {
    loadCities(prefectureSelect.value, <%= @post.city_id.to_json %>);
  }
});
</script>

app/views/posts/_post.html.erb
<div class="col-12 card mb-3 text-decoration-none shadow fadeUp" onclick="handleCardClick(event, '<%= post_path(post.id) %>')" style="cursor: pointer;">
  <div class="card-body">
    <div class="d-flex mb-2">
      <%= link_to post.user.name, user_path(post.user), class: "link-dark name-link", onclick: "event.stopPropagation();" %>
      <div class="area-box ms-2"><%= post.prefecture.name %></div>
      <div class="area-box ms-2"><%= post.city.name %></div>
      <% if current_user %>
        <% if post.user_id != current_user.id %>
          <div class="ms-auto bookmark-star"><%= render 'bookmarks/bookmark_button', { post: post } %></div>
          <div>
            <%= link_to post_path(post.id), id: "map", data: { bs_toggle: "tooltip", bs_placement: "top" }, title: "地図を見る", onclick: "event.stopPropagation();" do %>
              <i class="fa-solid fa-location-dot" style="color: #185a9d;"></i>
            <% end %>
          </div>
        <% else %>
          <div class="ms-auto">
            <%= link_to post_path(post.id), id: "map", data: { bs_toggle: "tooltip", bs_placement: "top" }, title: "地図を見る", onclick: "event.stopPropagation();" do %>
              <i class="fa-solid fa-location-dot" style="color: #185a9d;"></i>
            <% end %>
          </div>
        <% end %>
      <% else %>
        <div class="ms-auto">
          <%= link_to post_path(post.id), id: "map", data: { bs_toggle: "tooltip", bs_placement: "top" }, title: "地図を見る", onclick: "event.stopPropagation();" do %>
            <i class="fa-solid fa-location-dot" style="color: #185a9d;"></i>
          <% end %>
        </div>
      <% end %>
    </div>
    <p class="mb-0"><%= post.content %></p>
    <small class="mb-0 d-flex flex-row-reverse"><%= l post.created_at %></small>
  </div>
</div>

<script>
  function handleCardClick(event, url) {
    // クリックされた要素がリンク以外の場合のみページ遷移
    if (!event.target.closest("a")) {
      window.location.href = url;
    }
  }
</script>

app/views/posts/_searchform.html.erb
<%= search_form_for @q do |f| %>
  <div class="d-flex" id="search">
    <div class="form-group">
      <%= f.collection_select :prefecture_id_eq, Prefecture.all, :id, :name, { prompt: "都道府県" }, { class: "form-select form-select-lg prefecture-box" } %>
    </div>
    <div class="form-group mx-2">
      <%= f.collection_select :city_id_eq, City.where(prefecture_id: params.dig(:q, :prefecture_id_eq)), :id, :name, { prompt: "市区町村", selected: params.dig(:q, :city_id_eq) }, { class: "form-select form-select-lg city-box" } %>
    </div>
    <div class="actions form-group ms-auto">
      <%= f.submit "検索", class: "btn btn-lg text-light search-button" %>
    </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<%= javascript_include_tag "prefecture_city_select" %>
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-10 card shadow">
      <div class="card-body">
        <div class="col-lg-8 offset-lg-2">
          <h2 class="pb-4 text-center"><%= t('.title') %></h2>
          <%= render 'form', { post: @post } %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<%= javascript_include_tag "searchform" %>

<div class="loader-wrap">
  <div class="loader">Loading...</div>
</div>

<div class="container mt-5">
  <div class="row">
    <div class="col-12">
      <div class="d-flex justify-content-center">
        <div class="mb-5">
          <%= render 'searchform', q: @q, data: { turbo: false } %>
        </div>
      </div>
      <div>
        <% if @prefecture.present? && @city.present? %>
          <h4>
            <%= @prefecture.name %> <%= @city.name %> の結果 <%= @count %> 件
          </h4>
        <% else %>
          <% if @prefecture.present? %>
            <h4>
              <%= @prefecture.name %> の結果 <%= @count %> 件
            </h4>
          <% end %>
        <% end %>
      </div>
      <%= render partial: 'post', collection: @posts, as: :post %>
      <div class="d-flex justify-content-center">
        <%= paginate @posts, theme: 'bootstrap-5' %>
      </div>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<% breadcrumb :post_new %>
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <div class="col-12 card shadow mb-5">
        <div class="card-body">
          <h2 class="pb-4 text-center"><%= t('.title') %></h2>
          <%= render 'form', { post: @post } %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<%= javascript_include_tag "google_map" %>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAPS_API_KEY'] %>&callback=initMap&v=weekly&libraries=marker" defer></script>
<script src="https://accounts.google.com/gsi/client" async></script>

<div class="loader-wrap">
  <div class="loader">Loading...</div>
</div>
<% breadcrumb :post_show, @post, @prefecture, @city %>

<div class="post-modal js-modal">
  <div class="post-modal-container">
    <div class="post-modal-content">
      <p>投稿しました！</p>
      <button type="button" class="btn btn-outline-secondary mb-2 w-75 mx-auto" id="continue-posting">続けて投稿する</button>
      <button type="button" class="btn btn-outline-secondary mb-2 w-75 mx-auto" id="go-home">ホームに戻る</button>
    </div>
    <div class="post-modal-close js-modal-close">✕</div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <article class="card shadow">
        <div class="card-body p-5">
          <div class="row">
            <div>
              <ul class="list-inline mb-5">
                <li class="list-inline-item"><%= link_to @post.user.name, user_path(@post.user), class: "text-decoration-none link-dark name-link" %></li>
                <li class="list-inline-item area-box"><%= @post.prefecture.name %></li>
                <li class="list-inline-item area-box"><%= @post.city.name %></li>
              </ul>
            </div>
            <div class="container mb-3">
              <div class="row justify-content-center">
                <div class="col-11">
                  <h5><%= @post.content %></h5>
                </div>
              </div>
            </div>
          </div>

          <div class="d-flex flex-row-reverse border-top border-dark mt-5 pt-3">
            <% if current_user && current_user.own?(@post) %>
              <%= link_to post_path(@post), data: { turbo_method: :delete, turbo_confirm: "削除しますか？", bs_toggle: "tooltip", bs_placement: "top" }, title: "投稿を削除" do %>
                <i class="fa-solid fa-trash-can" style="color: #185a9d;"></i>
              <% end %>
              <%= link_to edit_post_path(@post), id: "button-edit-#{@post.id}", data: { bs_toggle: "tooltip", bs_placement: "top" }, title: "投稿を編集" do %>
                <i class="fa-solid fa-pen-to-square" style="color: #185a9d; margin-right: 15px;"></i>
              <% end %>              
            <% else %>
              <div class="bookmark-star" style="margin-right: 0px;"><%= render 'bookmarks/bookmark_button', { post: @post } %></div>
            <% end %>
            <%= link_to "https://twitter.com/intent/tweet?text=【#{ ERB::Util.url_encode(@post.prefecture.name) }】【#{ ERB::Util.url_encode(@post.city.name) }】%0a#{ ERB::Util.url_encode(@post.content) }%0a%0a%23Jimotter%0a&url=#{ ERB::Util.url_encode(post_url(@post)) }", target: '_blank', rel: "noopener noreferrer", data: { bs_toggle: "tooltip", bs_placement: "top" }, title: "Xで共有する" do %>
              <i class="fa-brands fa-x-twitter" style="color: #185a9d; margin-right: 15px;"></i>
            <% end %>
          </div>
          <div class="d-flex flex-row-reverse my-3">
            <small><%= l @post.created_at %></small>
          </div>

          <div id="map" style="height: 500px; width: 100%;" class="mb-3" 
              data-latitude="<%= @post.latitude %>" 
              data-longitude="<%= @post.longitude %>">
          </div>

          <div class="mt-4">
            <%= render 'comments/form', comment: @comment, post: @post %>
          </div>
          <div id="comments">
            <%= render @comments %>
          </div>
        </div>
      </article>
    </div>
  </div>
</div>

<script>
document.addEventListener("turbo:load", function() {
  const modal = document.querySelector('.js-modal'),
        close = document.querySelector('.js-modal-close');
  const successMessage = "<%= flash[:notice] %>"; // コントローラーで設定したフラッシュメッセージを取得

  if (successMessage) {
    modal.classList.add('is-active');
  }

  function modalClose() {
    modal.classList.remove('is-active');
  }
  close.addEventListener('click', modalClose);

  //「モーダルの外側」をクリックしてモーダルを閉じる
  function modalOut(e) {
    if (e.target == modal) {
      modal.classList.remove('is-active');
    }
  }
  addEventListener('click', modalOut);

  // ボタンのクリックイベント
  document.getElementById("continue-posting").addEventListener("click", function() {
    window.location.href = "/posts/new";
  });

  document.getElementById("go-home").addEventListener("click", function() {
    window.location.href = "/";
  });
});
</script>